In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('price.csv', sep=';')
df

    id                                              title  price
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....   10.0
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...    NaN
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...    7.0
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....   35.0
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...   11.0
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...   15.0
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...    NaN
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...   10.0

In [3]:
df['two'] = 2

In [4]:
df

    id                                              title  price  two
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....   10.0    2
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...    NaN    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...    7.0    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....   35.0    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...   11.0    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...   15.0    2
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...    NaN    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...   10.0    2

In [5]:
df['id_copy'] = df.id

In [6]:
df

    id                                              title  price  two  id_copy
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....   10.0    2        1
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...    NaN    2        2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...    7.0    2        3
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0    2        4
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....   35.0    2        5
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0    2        6
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...   11.0    2        7
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0    2        8
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...   15.0    2        9
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...    NaN    2       10
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...   10.0    2       11

In [7]:
df['total'] = df.price * df.two

In [8]:
df

,id,title,price,two,id_copy,total
0,1,Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....,10.0,2,1,20.0
1,2,Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...,NaN,2,2,NaN
2,3,Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...,7.0,2,3,14.0
3,4,Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...,25.0,2,4,50.0
4,5,Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....,35.0,2,5,70.0
5,6,Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...,5.0,2,6,10.0
6,7,"Ноутбук Apple MacBook Air 13"" 256GB 2020 Space...",11.0,2,7,22.0
7,8,Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...,16.0,2,8,32.0
8,9,Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...,15.0,2,9,30.0
9,10,Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...,NaN,2,10,NaN
10,11,Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...,10.0,2,11,20.0

In [11]:
cities = pd.read_csv('city.csv', sep=';')
cities

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [12]:
cities['Location'] = cities.Name + ', ' + cities.CountryCode

In [13]:
cities

,ID,Name,CountryCode,District,Population,Location
0,1,Kabul,AFG,Kabol,1780000,"Kabul, AFG"
1,2,Qandahar,AFG,Qandahar,237500,"Qandahar, AFG"
2,3,Herat,AFG,Herat,186800,"Herat, AFG"
3,4,Mazar-e-Sharif,AFG,Balkh,127800,"Mazar-e-Sharif, AFG"
4,5,Amsterdam,NLD,Noord-Holland,731200,"Amsterdam, NLD"
...,...,...,...,...,...,...
4074,4075,Khan Yunis,PSE,Khan Yunis,123175,"Khan Yunis, PSE"
4075,4076,Hebron,PSE,Hebron,119401,"Hebron, PSE"
4076,4077,Jabaliya,PSE,North Gaza,113901,"Jabaliya, PSE"
4077,4078,Nablus,PSE,Nablus,100231,"Nablus, PSE"
4078,4079,Rafah,PSE,Rafah,92020,"Rafah, PSE"

In [14]:
df

,id,title,price,two,id_copy,total
0,1,Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....,10.0,2,1,20.0
1,2,Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...,NaN,2,2,NaN
2,3,Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...,7.0,2,3,14.0
3,4,Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...,25.0,2,4,50.0
4,5,Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....,35.0,2,5,70.0
5,6,Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...,5.0,2,6,10.0
6,7,"Ноутбук Apple MacBook Air 13"" 256GB 2020 Space...",11.0,2,7,22.0
7,8,Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...,16.0,2,8,32.0
8,9,Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...,15.0,2,9,30.0
9,10,Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...,NaN,2,10,NaN
10,11,Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...,10.0,2,11,20.0

In [17]:
df.drop('total', axis=1)

    id                                              title  price  two  id_copy
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....   10.0    2        1
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...    NaN    2        2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...    7.0    2        3
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0    2        4
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....   35.0    2        5
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0    2        6
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...   11.0    2        7
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0    2        8
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...   15.0    2        9
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...    NaN    2       10
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...   10.0    2       11

In [18]:
df

,id,title,price,two,id_copy,total
0,1,Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....,10.0,2,1,20.0
1,2,Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...,NaN,2,2,NaN
2,3,Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...,7.0,2,3,14.0
3,4,Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...,25.0,2,4,50.0
4,5,Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....,35.0,2,5,70.0
5,6,Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...,5.0,2,6,10.0
6,7,"Ноутбук Apple MacBook Air 13"" 256GB 2020 Space...",11.0,2,7,22.0
7,8,Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...,16.0,2,8,32.0
8,9,Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...,15.0,2,9,30.0
9,10,Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...,NaN,2,10,NaN
10,11,Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...,10.0,2,11,20.0

In [20]:
df.drop(columns=['total', 'id_copy'],
        axis=1,
        inplace=True)

In [21]:
df

    id                                              title  price  two
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....   10.0    2
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...    NaN    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...    7.0    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....   35.0    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...   11.0    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...   15.0    2
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...    NaN    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...   10.0    2

In [22]:
df.drop([1, 9])

    id                                              title  price  two
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....   10.0    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...    7.0    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....   35.0    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...   11.0    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...   15.0    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...   10.0    2

In [26]:
df.drop(df.loc[df.price.isna(), :].index)

    id                                              title  price  two
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....   10.0    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...    7.0    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....   35.0    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...   11.0    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...   15.0    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...   10.0    2

In [27]:
df.dropna(subset=['price'])

    id                                              title  price  two
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....   10.0    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...    7.0    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....   35.0    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...   11.0    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...   15.0    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...   10.0    2

In [28]:
df.fillna(0)

    id                                              title  price  two
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....   10.0    2
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...    0.0    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...    7.0    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....   35.0    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...   11.0    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...   15.0    2
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...    0.0    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...   10.0    2